### PR TITLE
Add support for cells column row

### PR DESCRIPTION
**Pull request by iambumblehead**
related https://github.com/iambumblehead/render-thumb-for.sh/issues/26

------------------------------
this function does not work from inside vifm
```bash
# https://github.com/dylanaraps/pure-bash-bible
#  ?tab=readme-ov-file#get-the-terminal-size-in-pixels
wh_term_resolution_get () {
    # Usage: wh_term_resolution_get
    cmd=$(printf '%b' "${TMUX:+\\ePtmux;\\e}\\e[14t${TMUX:+\\e\\\\}")
    IFS=";t" read -d t -sra term_size -t 2 -p $cmd >&2
    printf '%s\n' "${term_size[1]} ${term_size[2]}"
}
```

### CODE REVIEW

**Comment by iambumblehead** [comment]
@xaizek from within vifm, there is no way for the script to detect the resolution of the window. Do you know of a way the script could obtain resolution from vifm itself? Without window resolution, the script will be unable to calculate the size of the view area from colums and rows.

The window resolution function returns an empty string from within vifm and I believe it is due to reduced privileges when the script is spawned indirectly. For example inside vifm the script was not allowed to call `stty size` to return lines and columns and a [different way needed to be used.](https://github.com/iambumblehead/render-thumb-for.sh/pull/27/commits/cb9bf5b81d9c937f5f63fd57368a2b3a4744168c)

I'll wait for your input (politely) before a make any subsequent changes or plans.

**Comment by iambumblehead** [comment]
@xaizek I'm interested to know what you think of an idea I've just had... when searching various things, I came across repeated monospace font dimensions a few times such as 8x16 pixels and 32x64 pixels. Perhaps these are "standard" sizes the script could rely on? I did not find anything authoritative to confirm this theory.

Here, for example, is a monospace font on github available in the following sizes https://github.com/fcambus/spleen: 5x8, 6x12, 8x16, 12x24, 16x32, 32x64 and when searching I found mention of similar font-sizes published by IBM and Arduino. I also noticed the trial-by-error "multiplier" values I settled on for vifm were "29 64" very close to "32x64".

If resolution cannot be programmatically detected, maybe render-thumb-for.sh could support three standard resolutions "low" (12x24), "mid" (12x24) and "high" (32x64) and "high" could be used as the default cell resolution. If the user needed to customize the resolution they could pass in an additional parameter to do so, eg -r 40x64.

Do you think this idea is safe/good?

For my own later-reference, it might be useful for me to read parts of these
 * https://gitlab.gnome.org/GNOME/vte/-/issues/312
 * https://en.wikipedia.org/wiki/Glyph_Bitmap_Distribution_Format

**Comment by xaizek** [comment]
I think font sizes can be pretty much anything.  It's not even fixed by a combination of font and its size as you can change distance between lines and characters.  The "standard" sizes are probably specific to bitmap fonts for use with native consoles rather than with terminal emulators.

For `stty` and such adding [`%N` macro](https://vifm.info/vimdoc.shtml#vifm-%25N) to `fileviewer` command should help.  By default, viewer can't access terminal so it can't mess up its state.

**Comment by iambumblehead** [comment]
I tried adding %N to vifm's fileviewer command, but the resolution function still returns empty. 
```bash
render-thumb-for.sh -c %c %pw %ph %N
```
Also, inside the script `echo "$(stty size)"` prints "standard input inappropriate ioctl for device" from inside vifm, but prints "21 120" when the script runs directly from terminal. Based on my understanding stty should be usable I wonder if I am using %N wrong

**Comment by iambumblehead** [comment]
uberzug uses an ioctl utility to [probe width and height](https://github.com/ueber-devel/ueberzug/blob/a5922f8466d324cf91e91a6b6f92b004162a3ae1/ueberzug/terminal.py#L17-L21)

-------------------------------------------
I searched ways a bash script might follow uberzug's ioctl winsize request, to obtain the pixel resolution of window. In [summary of the link,](https://unix.stackexchange.com/questions/213799/can-bash-write-to-its-own-input-stream#answer-217390) it is not possible to send ioctl calls directly from bash. The user at the link shows ways ioctl-using script strings can be sent to perl, python and ruby runtimes. It also shows how to create a little c binary that makes an ioctl call.

Searching "ioctl" at the arch repositories returns empty results.

@xaizek do you think it is a good idea for this script to check for perl|python|ruby runtimes and try using one of those to build a winsize ioctl request? What do you recommend?

related link,
 * [someone shares github](https://stackoverflow.com/questions/8082302/how-to-invoke-ioctl-in-shell-script) sources to c sources used to send ioctl requests from bash script
 * [ioctl winsize, python](https://gist.github.com/jtriley/1108174) calls gist with messages left by other users
 * [ioctl winsize, another python](https://gist.github.com/sbz/bca2d1327910e0d8cadff1835625cbf2)
 * [ioctl winsize, perl](https://www.perlmonks.org/?node_id=899777)
 * [ioctl winsize, c, gist](https://gist.github.com/sbz/4ba35bdaf51629216dbce84636a4cccf)
 * [ioctl winsize, rust](https://hermanradtke.com/2015/01/12/terminal-window-size-with-rust-ffi.html/)
 * [ttyio spec](https://refspecs.linuxbase.org/LSB_5.0.0/LSB-Core-generic/LSB-Core-generic/baselib-ttyio-2.html) and [arch-hosted ttyio spec](https://man.archlinux.org/man/ioctl_tty.2.en) `Note: The number of columns stored in ws_col assumes that the terminal device is using a mono-spaced font.`
 * [informative console-tools, writevt](https://unix.stackexchange.com/questions/406690/force-output-to-input-buffer-like-0336n-in-a-script) possible ioctl alternative, and a not-working perl one-liner

**Comment by iambumblehead** [comment]
possibly the %N macro is used incorrectly here. The fileviewer command looks like this,
```bash
render-thumb-for.sh -c %c %pw %ph %N
```
Inside the script `echo "$(stty size)"` prints an empty string from inside vifm, but prints "21 120" when the script runs directly from terminal.

**Comment by iambumblehead** [comment]
Control sequences to return window resolution and cell pixel size,
 * iTerm2 proprietary control sequence https://iterm2.com/documentation-escape-codes.html
 * foot/xterm control sequences https://www.mankier.com/7/foot-ctlseqs

Unfortunately, xterm control sequences return empty values when run from "inside" vifm. They do, however, return values when the script runs directly from shell
```bash
IFS=";" read -a winsize -s -t ${timeoutss} -d "t" -p $'\e[14t' >&2
echo "window resolution ${winsize[2]} ${winsize[1]}" # window resolution 696 469 (correct)
IFS=";" read -a cellsize -s -t ${timeoutss} -d "t" -p $'\e[16t' >&2
echo "cell size ${cellsize[2]} ${cellsize[1]}" # cell size 10 21 (seems wrong)
```

**Comment by iambumblehead** [comment]
unfortunately, these control sequences return empty values when they are run from "inside" vifm, however they do return values when the script is run directly from shell https://www.mankier.com/7/foot-ctlseqs
```bash
IFS=";" read -a winsize -s -t ${timeoutss} -d "t" -p $'\e[14t' >&2
echo "window resolution ${winsize[2]} ${winsize[1]}" # window resolution 696 469
IFS=";" read -a cellsize -s -t ${timeoutss} -d "t" -p $'\e[16t' >&2
echo "cell size ${cellsize[2]} ${cellsize[1]}" # cell size 10 21
```

**Comment by xaizek** [comment]
> I tried adding %N to vifm's fileviewer command, but the resolution function still returns empty.

That's because it uses `/dev/stdin` by default which is redirected by Vifm.  This doesn't work:
```
:!stty size %N%q
```
this works:
```
:!stty -F /dev/tty size %N%q
```

`ioctl()` API is what `stty` uses, so either they both work or neither.

**Comment by iambumblehead** [comment]
@xaizek thank you this does show lines and columns from inside vifm!
```bash
echo "size $(stty -F /dev/tty size)"
```

Do you know what changes should be made to these read calls to make them use /dev/tty? I've tried various things like appending "< /dev/tty" to the end but they always return empty inside vifm,
```bash
IFS=";" read -a winsize -s -t ${timeoutss} -d "t" -p $'\e[14t' >&2
IFS=";" read -a cellsize -s -t ${timeoutss} -d "t" -p $'\e[16t' >&2

IFS=";" read -a winsize -s -t ${timeoutss} -d "t" -p $'\e[14t' < /dev/tty # empty
```

> ioctl() API is what stty uses, so either they both work or neither.

Thank you for helping me without your help would have been stuck

related,
 * [read control sequence from /dev/tty,](https://stackoverflow.com/questions/47938109/reading-answer-to-control-string-sent-to-xterm) stackoverflow
 * [suggestion](https://stackoverflow.com/questions/32968728/bash-write-on-device-then-read-from-it#answer-32969280) to keep /dev/tty open, `exec 3<> /dev/tty`

**Comment by xaizek** [comment]
Not sure why, but adding `2>/dev/tty` seems to work.

**Comment by iambumblehead** [comment]
No success here with this or variations thereof, as well as `read -u $fd` winsize is always empty,
```bash
IFS=";" read -a winsize -s -t 2 -d "t" -p $'\e[14t' 2>/dev/tty
```

These lines _almost_ work here. Sometimes the full resolution is not displayed and there some junk characters added to vifm so that pressing ":" starts with input ":.,.+8:q"
```bash
echo -e '\e[14t' > /dev/tty
IFS=";" read -a winsize -s -t 2 -d "t" < /dev/tty
```

related,
 * [question at kitty](https://github.com/kovidgoyal/kitty/discussions/7215) he replied but thinks the question should be directed at vifm and recommends kitty's custom interface for probing window details, so his answer is not portable for xterm
 * [question at tmux](https://github.com/orgs/tmux/discussions/3565#discussioncomment-8767664) they might ignore me but people there are highly qualified to answer. <strike>no answer yet</strike> one reply, but I don't understand the reply and am cautious about alienating myself there with too many novice questions.

**Comment by iambumblehead** [comment]
These lines _almost_ work here. Sometimes the full resolution is not displayed and there some junk characters added to vifm so that pressing ":" starts with input ":.,.+8:q"
```bash
echo -e '\e[14t' > /dev/tty
IFS=";" read -a winsize -s -t ${timeoutss} -d "t" < /dev/tty
```

**Comment by xaizek** [comment]
> * [question at kitty](https://github.com/kovidgoyal/kitty/discussions/7215) he replied but thinks the question should be directed at vifm and recommends kitty's custom interface for probing window details, so his answer is not portable for xterm

It's the same `ioctl()` that's used by `stty size`.  How well it works might depend on terminal emulator, but luckily has nothing to do with Kitty.

> These lines _almost_ work here. Sometimes the full resolution is not displayed and there some junk characters added to vifm so that pressing ":" starts with input ":.,.+8:q"

That's pretty much what the answer in tmux discussions told you.  The terminal is in use by Vifm and it gets the answer to the query sent by your script taking it for user's input.  I must have worked for me because I tested in `:!...` and not in `fileviewer` in which case Vifm doesn't try to read from the terminal until the command is done.  `ioctl()` doesn't have such issues, but using it from bash is a problem.  You can try adding [`%pu` macro](https://vifm.info/vimdoc.shtml#vifm-%25pu) in addition to already used `%N`.  This disables caching and makes Vifm wait until the command is done (so no asynchronous preview), this way it shouldn't interfere with the script's use of the terminal.

**Comment by iambumblehead** [comment]
@xaizek using `%pu` works each time. Full resolution is seen in the view area and input area is clean when entering input mode to quit.

>  This disables caching and makes Vifm wait until the command is done (so no asynchronous preview),

question: Is there a way windowsize query could run separately synchronous, so rendering could continue running asynchronously? The script needs `%pu` behaviour for a few escape sequence queries only, which do return values quickly: windowsize query `\e[14t`, issixelsupport query `\e[c`, sixelmaxpixelsize query `\e[?2;4;0S`

Specifically, these are ideas I have, but maybe these are not possible,
 * **Run a windowsize query synchronously and save the results to a file,** then asynchronously run render-thumb-for.sh afterward and tries catting the file for windowsize.
 * **Run a windowsize query synchronously and save the results to a variable,** then asynchronously run render-thumb-for.sh with windowsize param.

**Comment by xaizek** [comment]
The macros work per viewer, so that would need to execute two viewers in sequence which won't happen.  Viewer can also be implemented in Lua where you could do multiple things, but implementing asynchronous preview there will have issues as the API wasn't designed for it (first call won't have anything to return and the next call wan't happen automatically; reading job's output is also synchronous, but a temporary file could probably work around that).

**Comment by iambumblehead** [comment]
Thanks. It seems a single viewer using `%N %pu` is the "best" way to go, but has an undesirable side-effect of blocking the vifm ui. What do you think?

------------------
After updating the script to be used with vifm, `%N %pu` do not prevent junk characters from reaching screen 🥺



The only other ideas I can think of,
 * somehow write to tty and then erase or remove messages from tty, but even if it were possible, it seems too-involved to be reasonable (attempted to do this, but it broke the UI and is too involved for me, because I am not skilled or interested to know how it would be done).
 * if there were a vifm hook that could run a script before starting ncurses, the hook could be scripted to run normal escape queries with stdout in advance of ncurses to determine cell size, sixel support and sixel max width and height.

**Comment by iambumblehead** [comment]
found a bug in foot https://codeberg.org/dnkl/foot/issues/1643 there is actually an xterm escape sequence to request cell size which seemed inaccurate in foot and it will probably be resolved as well

**Comment by xaizek** [comment]
> It seems a single viewer using `%N %pu` is the "best" way to go, but has an undesirable side-effect of blocking the vifm ui. What do you think?

Well, it should at least work.

> * if there were a vifm hook that could run a script before starting ncurses, the hook could be scripted to run normal escape queries with stdout in advance of ncurses to determine cell size, sixel support and sixel max width and height.

This wouldn't address resizes.

> After updating the script to be used with vifm, `%N %pu` do not prevent junk characters from reaching screen

Did you drop `%pd`?  It looks like Sixel isn't being passed to terminal.

**Comment by iambumblehead** [comment]
@xaizek I think it is working with `%pd %pu %N` the preview is 3 times small because of the foot terminal issue linked above, but otherwise this seems to be working. I can't believe it. Thank you for helping me.

**Comment by iambumblehead** [comment]
hahaha I am so happy to see this

I can't believe it

**Comment by iambumblehead** [comment]
> This wouldn't address resizes.

The terminal can be queried to report cell size. The script hasn't been doing it because values returned from foot were wrong, but it is fixed at foot upstream now.

If we saved the terminal's reported cell size and instead used cell size to calculate available pixel area from rows and columns, vifm could resize without breaking the image script. Problems could occur on font resize, but if `%N %pu` were dropped it might be a good trade overall.

I'm an appreciative vifm user with no expectation, but if you were to add a hook to allow stdout queries before ncurses starts, I would update this script to support preferred optional usage of the hook.

Anyway, thank you for helping me thus far :)

**Comment by iambumblehead** [comment]
I experimented with kitty's image placement and basically and it gives two ways to place an image;
  1. provide all values: top and left position, width and height or,
  2. render the image at the cursor with no control of size

I did not find a way to make the first way work, so I believe kitty will require images pre-generated to exactly the scale of vifm's view area.

**Comment by iambumblehead** [comment]
I was trying to delete some text in the comment text area and accidentally hit `[Close with comment]`

**Comment by xaizek** [comment]
> If we saved the terminal's reported cell size and instead used cell size to calculate available pixel area from rows and columns, vifm could resize without breaking the image script.

You don't need `ncurses` to not be initialized, just for Vifm to not process input.  Simply running a command from `vifmrc` should do (e.g. `let $BLA = system('cmd')`, `:let` is needed because there is no `:call` (probably worth adding)).

**Pull request merged**
